micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/nossacasadocodigo
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: desafios
    dialect: org.hibernate.dialect.MySQL8Dialect

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update